//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IContractsInfoService")]
    public interface IContractsInfoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContractsInfoService/GetData", ReplyAction="http://tempuri.org/IContractsInfoService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContractsInfoService/GetData", ReplyAction="http://tempuri.org/IContractsInfoService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContractsInfoService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IContractsInfoService/GetDataUsingDataContractResponse")]
        WcfServiceExample.CompositeType GetDataUsingDataContract(WcfServiceExample.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContractsInfoService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IContractsInfoService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<WcfServiceExample.CompositeType> GetDataUsingDataContractAsync(WcfServiceExample.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContractsInfoService/GetContractsInfo", ReplyAction="http://tempuri.org/IContractsInfoService/GetContractsInfoResponse")]
        WcfServiceExample.ContractInfo[] GetContractsInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContractsInfoService/GetContractsInfo", ReplyAction="http://tempuri.org/IContractsInfoService/GetContractsInfoResponse")]
        System.Threading.Tasks.Task<WcfServiceExample.ContractInfo[]> GetContractsInfoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IContractsInfoServiceChannel : WcfClient.ServiceReference1.IContractsInfoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContractsInfoServiceClient : System.ServiceModel.ClientBase<WcfClient.ServiceReference1.IContractsInfoService>, WcfClient.ServiceReference1.IContractsInfoService {
        
        public ContractsInfoServiceClient() {
        }
        
        public ContractsInfoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContractsInfoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContractsInfoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContractsInfoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public WcfServiceExample.CompositeType GetDataUsingDataContract(WcfServiceExample.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<WcfServiceExample.CompositeType> GetDataUsingDataContractAsync(WcfServiceExample.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public WcfServiceExample.ContractInfo[] GetContractsInfo() {
            return base.Channel.GetContractsInfo();
        }
        
        public System.Threading.Tasks.Task<WcfServiceExample.ContractInfo[]> GetContractsInfoAsync() {
            return base.Channel.GetContractsInfoAsync();
        }
    }
}
